# -*- coding: utf-8 -*-
"""Untitled8.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1dcEEzGDzdC9ALZ5mexy2dFCEwX1v8tS0
"""

!pip3 install twilio

import os
from twilio.rest import Client 
 
account_sid = ''  #provisional 
auth_token = '[AuthToken]' 
client = Client(account_sid, auth_token) 
 
message = client.messages.create(  
    messaging_service_sid='', #provisional 
    body='Hi from twilio API',      
    to='' ) #account number
 
print(message.sid)

